command: sudo python training/train_net.py --config-file training/configs/mask_rcnn_R_50_FPN_1x.yaml --num-gpus 1 SOLVER.IMS_PER_BATCH 2 SOLVER.BASE_LR 0.0025 MODEL.WEIGHTS https://dl.fbaipublicfiles.com/detectron2/COCO-Detection/faster_rcnn_R_50_FPN_1x/137257794/model_final_b275ba.pkl  OUTPUT_DIR /artifacts/models/detectron
container: devopsbay/detectron2-cuda:v0
machineType: V100
modelPath: /artifacts
modelType: Pytorch
name: detectron2-paperspace-demo
projectId: <project id>
workspace: 'https://github.com/Paperspace/object-detection-segmentation.git'
datasetUri:
  - "s3://paperspace-tiny-coco/small_coco.zip"
datasetName:
  - "small_coco"
clusterId: <cluster id>